# Generated by Django 6.0.2 on 2026-02-06 22:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_team_shift_employeeprofile_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shift',
            name='team',
        ),
        migrations.AddField(
            model_name='shift',
            name='employee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='core.employeeprofile'),
            preserve_default=False,
        ),
    ]
